version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - ConnectionStrings__AppDbConnection=User ID=postgres;Password=postgres;Host=db;Port=5432;Database=hurry_up_haul;

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hurry_up_haul
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
